name: Sign and Notarize Mac terraform
on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true
jobs:
  sign-and-notarize-mac-cli:
    runs-on: macos-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SHORELINE_BUILD_AWS_KEY }}
          aws-secret-access-key: ${{ secrets.SHORELINE_BUILD_AWS_SEC }}
          aws-region: us-west-2
      - name: Download cli asset
        env:
          version: ${{ github.event.inputs.version }}
        run: |
          aws s3 cp s3://shoreline-terraform-provider/${version}/terraform-provider-shoreline_${version}_darwin_amd64 ./terraform-provider-shoreline_${version}_darwin_amd64
          aws s3 cp s3://shoreline-terraform-provider/${version}/terraform-provider-shoreline_${version}_darwin_arm64 ./terraform-provider-shoreline_${version}_darwin_arm64
      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
          p12-password: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}
      - name: Install create-dmg via HomeBrew for code signing and app notarization
        run: |
          brew tap create-dmg/create-dmg
          brew install create-dmg
      - name: Sign and notarize mac x86 cli
        env:
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
          version: ${{ github.event.inputs.version }}
        run: |
          mkdir amd64
          chmod 755 ./terraform-provider-shoreline_${version}_darwin_amd64
          mv ./terraform-provider-shoreline_${version}_darwin_amd64 ./amd64/terraform-provider-shoreline_${version}_darwin_amd64.command
          chmod 755 ./amd64/terraform-provider-shoreline_${version}_darwin_amd64.command
          codesign -s "E4C09D7E61638C54FFD01886C778C5474B9F958D" -f -v --timestamp --options runtime ./amd64/terraform-provider-shoreline_${version}_darwin_amd64.command
          xcrun notarytool store-credentials "notary_credentials" --apple-id "build@shorelinesoftware.com" --team-id "8BF8P3HDAA" --password "${{ secrets.AC_PASSWORD }}"
          create-dmg --notarize "notary_credentials" terraform-provider-shoreline_${version}_darwin_amd64.dmg ./amd64/
      - name: Sign and notarize mac M1 cli
        env:
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
          version: ${{ github.event.inputs.version }}
        run: |
          mkdir arm64
          chmod 755 ./terraform-provider-shoreline_${version}_darwin_arm64
          mv ./terraform-provider-shoreline_${version}_darwin_arm64 ./arm64/terraform-provider-shoreline_${version}_darwin_arm64.command
          chmod 755 ./arm64/terraform-provider-shoreline_${version}_darwin_arm64.command
          codesign -s "E4C09D7E61638C54FFD01886C778C5474B9F958D" -f -v --timestamp --options runtime ./arm64/terraform-provider-shoreline_${version}_darwin_arm64.command
          xcrun notarytool store-credentials "notary_credentials" --apple-id "build@shorelinesoftware.com" --team-id "8BF8P3HDAA" --password "${{ secrets.AC_PASSWORD }}"
          create-dmg --notarize "notary_credentials" terraform-provider-shoreline_${version}_darwin_arm64.dmg ./arm64/
      - name: Upload signed cli to S3
        env:
          version: ${{ github.event.inputs.version }}
        run: |
          aws s3 rm s3://shoreline-terraform-provider/${version}/terraform-provider-shoreline_${version}_darwin_amd64
          aws s3 cp ./terraform-provider-shoreline_${version}_darwin_amd64.dmg s3://shoreline-terraform-provider/${version}/terraform-provider-shoreline_${version}_darwin_amd64.dmg
          aws s3 rm s3://shoreline-terraform-provider/${version}/terraform-provider-shoreline_${version}_darwin_arm64
          aws s3 cp ./terraform-provider-shoreline_${version}_darwin_arm64.dmg s3://shoreline-terraform-provider/${version}/terraform-provider-shoreline_${version}_darwin_arm64.dmg
